---
deployment:
  tasks:
    - export DEPLOYPATH=/home/arssnweb/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp css/main.css $DEPLOYPATH
    - /bin/cp .github/ISSUE_TEMPLATE/bug_report.md
    - /bin/cp README.md
    - /bin/cp _config.yml
